services:
  backend:
    restart: on-failure
    build:
      context: ./backend
    ports: 
      - 6969:6969
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
      - POSTGRES_PASSWORD=password
      - PORT=6969
      - HOST=0.0.0.0
    volumes:
      - backups:/app/backups/
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "./target/release/backend"]
  db:
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  backups:
  postgres_data:
