services:
  backend:
    restart: on-failure
    build:
      context: ./backend
    ports: 
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
    depends_on:
      - db
  db:
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432 # TODO УДАЛИТЬ ПРОБРОС ПОРТОВ ДЛЯ БД НА РЕЛИЗЕ АТО ТОРЧАТЬ БУДЕТ (ну или записать это в уязвимости =) )
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:

